### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by shinima** [little-saga/comparisons#1]
- [x] Use blueprint UI
- [ ] ~~Implement `CallbackSolution4`, `AsyncSolution4` and `SagaSolution`~~
- [x] Print time info in log
